change commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,32 +7,49 @@ on:
 
 jobs:
   deploy:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
 
     steps:
+      #  Checkout code
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Create .env file
+      #  Setup SSH
+      - name: Setup SSH
         run: |
-          cat <<EOF > .env
-          DB_NAME=${{ secrets.DB_NAME }}
-          DB_USER=${{ secrets.DB_USER }}
-          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
-          DB_HOST=${{ secrets.DB_HOST }}
-          DB_PORT=${{ secrets.DB_PORT }}
+          mkdir -p ~/.ssh
+          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
-          BACKEND_PORT=${{ secrets.BACKEND_PORT }}
-          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
+      #  Deploy on EC2
+      - name: Deploy on EC2
+        run: |
+          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
+            set -e  # stop if any command fails
 
-          VITE_API_URL=${{ secrets.VITE_API_URL }}
+            cd /home/ubuntu/app
+
+            echo "Creating .env file"
+            cat <<EOT > .env
+            DB_NAME=${{ secrets.DB_NAME }}
+            DB_USER=${{ secrets.DB_USER }}
+            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
+            DB_HOST=${{ secrets.DB_HOST }}
+            DB_PORT=${{ secrets.DB_PORT }}
+
+            BACKEND_PORT=${{ secrets.BACKEND_PORT }}
+            FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
+
+            VITE_API_URL=${{ secrets.VITE_API_URL }}
+            EOT
+
+            echo "Stopping containers"
+            docker compose down || true
+
+            echo "Building and starting containers"
+            docker compose up -d --build
+
+            echo "Cleaning unused images"
+            docker system prune -f
           EOF
-
-      - name: Stop existing containers
-        run: docker compose down || true
-
-      - name: Build and start containers
-        run: docker compose up -d --build
-
-      - name: Cleanup unused images
-        run: docker system prune -f
